#!/usr/bin/env python2.7
# -*- coding:utf-8 -*-
# ipyview.py

import os, sys
import re
import numpy as np
#from datetime import datetime, timedelta
#from dateutil.parser import parse
#import matplotlib
#matplotlib.use('TkAgg')
#import matplotlib.pyplot as plt
#from mpl_toolkits.basemap import Basemap
#from matplotlib import mlab
import pandas as pd
from netCDF4 import Dataset
from pylab import *
from metlib.kits import *
from metlib.color import *
from metlib.lidar import *
from metlib.data.ipyview import *

from IPython import Config, embed

plt.ion()
speaker = sys.stdout
warner = sys.stderr

ipythonconfig = Config({
    'TerminalInteractiveShell': {'banner1': '', 'editor': 'vim', 'pylab': 'qt'}, 
    })

if __name__ == '__main__':
    remain_args = get_sys_argv([], [], [])
    
    globald = sys.modules['__main__'].__dict__
    if len(remain_args) == 1:
        loaded_data, loaded_type = load_everything(remain_args[0])
        print "----------------"
        if loaded_type == "basket":
            print "Loaded Basket variables:", loaded_data
        else:
            data = loaded_data
            print "file: %s, recognized as: %s" % (remain_args[0], loaded_type)
            print "  ", "data :"
            print data
    else:
        for i, fname in enumerate(remain_args):
            print "----------------"
            varname = 'data%d' % i
            loaded_data, loaded_type = load_everything(fname)
            if loaded_type == "basket":
                print "Loaded Basket variables:", loaded_data
            else:
                globald[varname] = loaded_data
                print "file: %s, recognized as: %s" % (fname, loaded_type)
                print "  ", varname, ":"
                print globald[varname]

    for varname, fname in _sys_argv_kwargs.iteritems():
        print "----------------"
        loaded_data, loaded_type = load_everything(fname, basket_dest=varname)
        if loaded_type == "basket":
            print "Loaded Basket file", fname, "into dict:", varname, ", which contains:", loaded_data
        else:
            globald[varname] = loaded_data
            print "file: %s, recognized as: %s" % (fname, loaded_type)
            print "  ", varname, ":"
            print globald[varname]

    embed(config=ipythonconfig)
