#!/usr/bin/env python2.7
# -*- coding:utf-8 -*-
# ipyview.py

import os, sys
import re
import numpy as np
#from datetime import datetime, timedelta
#from dateutil.parser import parse
#import matplotlib
#matplotlib.use('TkAgg')
#import matplotlib.pyplot as plt
#from mpl_toolkits.basemap import Basemap
#from matplotlib import mlab
import pandas as pd
from netCDF4 import Dataset
from pylab import *
from metlib.kits import *
from metlib.color import *
from metlib.lidar import *
from metlib.data.misc import *
from metlib.data.misc import *
from metlib.data.boundary import *
from metlib.data.ipyview import *

from IPython import embed

plt.ion()

if __name__ == '__main__':
    remain_args = get_sys_argv([], [], [])
    ipyview(*remain_args, **_sys_argv_kwargs)
    embed()
