#!/bin/csh -f

${G3S}/sys/util/REQUIRE ./G3S_require
set reqres = $?
if ( "$reqres" != "0" ) then
	echo '    Error: Requirement not fulfilled. Exiting.'
	exit 1
else
	echo "    All requirements fulfilled, Running this part's job ... "
endif

if ( -x "./G3S_run" ) then
	echo RUNNING > ./G3S_status
	if ( -e "./G3S_runrc.csh" ) then
		source ./G3S_runrc.csh
	endif
	./G3S_run
	set runres = $?	
else 
	set runres = 0
endif

if ( -x "./G3S_check" ) then
	./G3S_check
	set chkres = $?
else
	set chkres = 0
endif

if ( "$runres" == "0" && "$chkres" == "0" ) then
	echo SUCCESS > ./G3S_status
	exit 0
else
	echo FAILED > ./G3S_status
	exit 1
endif

