#!/bin/csh -f

cd `dirname $0`
if ( -x ./G3S_runrc.csh ) then
	source ./G3S_runrc.csh
endif

# # TODO: Add check commands here.
# # metamet/shell/check_file_size may help.
if ( -e ./part2_output.txt ) then
	echo "Check passed"
	exit 0
else
	echo "Check failed"
	exit 1
endif

